import type {
  Account,
  Transaction,
  Invoice,
  Budget,
  KPIData,
  ExchangeRate,
  CashFlowData,
} from "@/types";

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "İş Bankası Vadesiz",
    type: "checking",
    iban: "TR12 0006 4000 0011 2345 6789 01",
    balance: 284_500.75,
    currency: "TRY",
    bankName: "Türkiye İş Bankası",
    cardNumber: "**** **** **** 4521",
  },
  {
    id: "acc-2",
    name: "İş Bankası Tasarruf",
    type: "savings",
    iban: "TR12 0006 4000 0011 2345 6789 02",
    balance: 150_000.0,
    currency: "TRY",
    bankName: "Türkiye İş Bankası",
  },
  {
    id: "acc-3",
    name: "Döviz Hesabı USD",
    type: "checking",
    iban: "TR12 0006 4000 0011 2345 6789 03",
    balance: 8_420.5,
    currency: "USD",
    bankName: "Türkiye İş Bankası",
  },
  {
    id: "acc-4",
    name: "Kredi Kartı",
    type: "credit",
    iban: "TR12 0006 4000 0011 2345 6789 04",
    balance: -12_340.0,
    currency: "TRY",
    bankName: "Türkiye İş Bankası",
    cardNumber: "**** **** **** 8823",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    date: "2026-07-03",
    description: "ABC Ltd. Hizmet Faturası",
    amount: 45_000,
    type: "credit",
    category: "Gelir",
    status: "completed",
    accountId: "acc-1",
    counterparty: "ABC Ltd. Şirketi",
    transactionType: "eft",
  },
  {
    id: "txn-2",
    date: "2026-07-03",
    description: "Ofis Kirası Temmuz",
    amount: 28_000,
    type: "debit",
    category: "Kira",
    status: "completed",
    accountId: "acc-1",
    counterparty: "Gayrimenkul AŞ",
    transactionType: "havale",
  },
  {
    id: "txn-3",
    date: "2026-07-02",
    description: "XYZ Yazılım Projesi",
    amount: 72_500,
    type: "credit",
    category: "Gelir",
    status: "completed",
    accountId: "acc-1",
    counterparty: "XYZ Teknoloji",
    transactionType: "fast",
  },
  {
    id: "txn-4",
    date: "2026-07-02",
    description: "Maaş Ödemeleri",
    amount: 95_000,
    type: "debit",
    category: "Personel",
    status: "completed",
    accountId: "acc-1",
    counterparty: "Bordro",
    transactionType: "havale",
  },
  {
    id: "txn-5",
    date: "2026-07-01",
    description: "Sunucu Barındırma",
    amount: 3_200,
    type: "debit",
    category: "Teknoloji",
    status: "completed",
    accountId: "acc-1",
    counterparty: "AWS Turkey",
    transactionType: "pos",
  },
  {
    id: "txn-6",
    date: "2026-07-01",
    description: "Danışmanlık Ücreti",
    amount: 18_000,
    type: "credit",
    category: "Gelir",
    status: "pending",
    accountId: "acc-1",
    counterparty: "Danışman AŞ",
    transactionType: "eft",
  },
  {
    id: "txn-7",
    date: "2026-06-30",
    description: "Elektrik Faturası",
    amount: 4_850,
    type: "debit",
    category: "Fatura",
    status: "completed",
    accountId: "acc-1",
    counterparty: "TEDAŞ",
    transactionType: "other",
  },
  {
    id: "txn-8",
    date: "2026-06-30",
    description: "Yazılım Lisansları",
    amount: 12_400,
    type: "debit",
    category: "Teknoloji",
    status: "completed",
    accountId: "acc-1",
    counterparty: "Microsoft",
    transactionType: "pos",
  },
  {
    id: "txn-9",
    date: "2026-06-29",
    description: "Müşteri Ödemesi",
    amount: 33_750,
    type: "credit",
    category: "Gelir",
    status: "completed",
    accountId: "acc-1",
    counterparty: "Delta Corp",
    transactionType: "fast",
  },
  {
    id: "txn-10",
    date: "2026-06-28",
    description: "Reklam Gideri",
    amount: 7_500,
    type: "debit",
    category: "Pazarlama",
    status: "failed",
    accountId: "acc-1",
    counterparty: "Meta AŞ",
    transactionType: "pos",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "FTR-2026-001",
    clientName: "ABC Ltd.",
    issueDate: "2026-07-01",
    dueDate: "2026-07-31",
    amount: 45_000,
    status: "paid",
    items: [
      { description: "Web Geliştirme Hizmeti", quantity: 1, unitPrice: 45_000, total: 45_000 },
    ],
  },
  {
    id: "inv-2",
    invoiceNumber: "FTR-2026-002",
    clientName: "XYZ Teknoloji",
    issueDate: "2026-07-02",
    dueDate: "2026-08-01",
    amount: 72_500,
    status: "pending",
    items: [
      { description: "Yazılım Projesi - Faz 1", quantity: 1, unitPrice: 50_000, total: 50_000 },
      { description: "Teknik Destek (Aylık)", quantity: 1, unitPrice: 22_500, total: 22_500 },
    ],
  },
  {
    id: "inv-3",
    invoiceNumber: "FTR-2026-003",
    clientName: "Delta Corp",
    issueDate: "2026-06-01",
    dueDate: "2026-06-30",
    amount: 33_750,
    status: "overdue",
    items: [
      { description: "Danışmanlık Hizmeti", quantity: 15, unitPrice: 2_250, total: 33_750 },
    ],
  },
  {
    id: "inv-4",
    invoiceNumber: "FTR-2026-004",
    clientName: "Gamma AŞ",
    issueDate: "2026-07-03",
    dueDate: "2026-08-02",
    amount: 18_000,
    status: "draft",
    items: [
      { description: "UI/UX Tasarım", quantity: 1, unitPrice: 18_000, total: 18_000 },
    ],
  },
  {
    id: "inv-5",
    invoiceNumber: "FTR-2026-005",
    clientName: "Beta Holding",
    issueDate: "2026-06-15",
    dueDate: "2026-07-15",
    amount: 120_000,
    status: "pending",
    items: [
      { description: "Kurumsal Yazılım Lisansı", quantity: 1, unitPrice: 120_000, total: 120_000 },
    ],
  },
];

export const mockBudgets: Budget[] = [
  { id: "bud-1", category: "Personel", limit: 100_000, spent: 95_000, period: "monthly", color: "hsl(var(--chart-1))", icon: "👥" },
  { id: "bud-2", category: "Kira", limit: 30_000, spent: 28_000, period: "monthly", color: "hsl(var(--chart-2))", icon: "🏢" },
  { id: "bud-3", category: "Teknoloji", limit: 20_000, spent: 15_600, period: "monthly", color: "hsl(var(--chart-3))", icon: "💻" },
  { id: "bud-4", category: "Pazarlama", limit: 15_000, spent: 7_500, period: "monthly", color: "hsl(var(--chart-4))", icon: "📢" },
  { id: "bud-5", category: "Fatura", limit: 10_000, spent: 4_850, period: "monthly", color: "hsl(var(--chart-5))", icon: "⚡" },
  { id: "bud-6", category: "Seyahat", limit: 8_000, spent: 2_200, period: "monthly", color: "hsl(var(--chart-1))", icon: "✈️" },
];

export const mockKPI: KPIData = {
  totalRevenue: 169_250,
  totalExpenses: 151_300,
  netProfit: 17_950,
  pendingInvoices: 5,
  pendingInvoicesAmount: 234_750,
  revenueChange: 12.4,
  expensesChange: -3.2,
  profitChange: 28.7,
  pendingChange: 2,
};

export const mockExchangeRates: ExchangeRate[] = [
  { currency: "USD/TRY", flag: "🇺🇸", rate: 38.42, change: 0.23 },
  { currency: "EUR/TRY", flag: "🇪🇺", rate: 41.85, change: -0.15 },
  { currency: "GBP/TRY", flag: "🇬🇧", rate: 48.67, change: 0.42 },
  { currency: "CHF/TRY", flag: "🇨🇭", rate: 43.21, change: 0.08 },
  { currency: "JPY/TRY", flag: "🇯🇵", rate: 0.268, change: -0.02 },
  { currency: "ALTIN/TRY", flag: "🥇", rate: 3_820.5, change: 15.3 },
];

export const mockCashFlow: CashFlowData[] = [
  { month: "Oca", gelir: 95_000, gider: 78_000 },
  { month: "Şub", gelir: 112_000, gider: 89_000 },
  { month: "Mar", gelir: 88_000, gider: 94_000 },
  { month: "Nis", gelir: 145_000, gider: 102_000 },
  { month: "May", gelir: 132_000, gider: 115_000 },
  { month: "Haz", gelir: 158_000, gider: 128_000 },
  { month: "Tem", gelir: 169_250, gider: 151_300 },
];